Repository wala/WALA, pull requests merged in 2021-09, with the labels that each got.

#944 Don't compile JSDT projects with Gradle
  settings.gradle
Labels: gradle

#946 Remove spurious IntelliJ IDEA metadata about a non-existent module
  .idea/WALA-fix.iml
  .idea/modules.xml
Labels: ide

#942 Save task providers for reuse a few lines later
  build.gradle
  com.ibm.wala.cast.java.ecj/build.gradle
  com.ibm.wala.cast.java.test.data/build.gradle
  com.ibm.wala.cast.js.nodejs/build.gradle
Labels: gradle, cleanup

#949 `compileTestJavaUsingEcj` depends on `downloadJLex`
  com.ibm.wala.cast.java.test.data/build.gradle
Labels: gradle

#950 Update Gradle 7 deprecations
  com.ibm.wala.core/build.gradle
Labels: gradle

#953 Give `autoLintGradle` task an empty output file
  build.gradle
Labels: gradle

#954 Avoid conditional dependencies
  build.gradle
  com.ibm.wala.cast.java.ecj/build.gradle
  com.ibm.wala.cast.java.ecj/gradle.lockfile
  com.ibm.wala.cast.js.nodejs/build.gradle
  com.ibm.wala.cast.js.nodejs/gradle.lockfile
  com.ibm.wala.cast/build.gradle
  com.ibm.wala.cast/gradle.lockfile
Labels: gradle

#956 Resolve linter-reported dependency problems
  .github/workflows/continuous-integration.yml
  build.gradle
  com.ibm.wala.cast.java.ecj/build.gradle
  com.ibm.wala.cast.java.ecj/gradle.lockfile
  com.ibm.wala.cast.java/gradle.lockfile
  com.ibm.wala.cast.js.html.nu_validator/gradle.lockfile
  com.ibm.wala.cast.js.nodejs/gradle.lockfile
  com.ibm.wala.cast.js.rhino/gradle.lockfile
  com.ibm.wala.cast.js/gradle.lockfile
  com.ibm.wala.cast/gradle.lockfile
  com.ibm.wala.core.java11/gradle.lockfile
  com.ibm.wala.core/gradle.lockfile
  com.ibm.wala.dalvik/gradle.lockfile
  com.ibm.wala.ide.jdt.test/build.gradle
  com.ibm.wala.ide.jdt.test/gradle.lockfile
  com.ibm.wala.ide.jdt/build.gradle
  com.ibm.wala.ide.jdt/gradle.lockfile
  com.ibm.wala.ide.jsdt.tests/build.gradle
  com.ibm.wala.ide.jsdt.tests/gradle.lockfile
  com.ibm.wala.ide.jsdt/gradle.lockfile
  com.ibm.wala.ide.tests/build.gradle
  com.ibm.wala.ide.tests/gradle.lockfile
  com.ibm.wala.ide/build.gradle
  com.ibm.wala.ide/gradle.lockfile
Labels: gradle

#977 Remove useless empty @throws tags
  com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/ecj/util/SourceDirCallGraph.java
Labels: cleanup

#978 Replace an anonymous class with a method reference
  com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/ecj/util/SourceDirCallGraph.java
Labels: cleanup

#979 Privatize protected members of final classes
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/PropagationCallGraphBuilder.java
Labels: cleanup

#984 Correct `-PexcludeSlowTests` build failures
  com.ibm.wala.ide.tests/build.gradle
  com.ibm.wala.ide.tests/gradle.lockfile
  com.ibm.wala.util/build.gradle
  com.ibm.wala.util/gradle.lockfile
Labels: gradle

#987 Remove unnecessary calls to `toString()`
  com.ibm.wala.cast.java/src/main/java/com/ibm/wala/cast/java/client/JavaSourceAnalysisEngine.java
  com.ibm.wala.cast.java/src/testFixtures/java/com/ibm/wala/cast/java/test/IRTests.java
  com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/html/SourceRegion.java
  com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/tree/rewrite/CAstRewriter.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/analysis/reflection/ReflectiveInvocationInterpreter.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/cfg/exc/intra/ParameterState.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/classLoader/AbstractNestedJarFileModule.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/classLoader/AbstractURLModule.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/client/AbstractAnalysisEngine.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/config/AnalysisScopeReader.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/scope/JUnitEntryPoints.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/ssa/ParameterAccessor.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/ssa/TypeSafeInstructionFactory.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/demandpa/alg/SimpleDemandPointsTo.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/demandpa/flowgraph/AbstractDemandFlowGraph.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/demandpa/flowgraph/SimpleDemandPointerFlowGraph.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/examples/analysis/dataflow/StaticInitializer.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/examples/drivers/PDFControlDependenceGraph.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/examples/drivers/PDFWalaIR.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/impl/Util.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/SSAPropagationCallGraphBuilder.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/cfa/CallStringContext.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/slicer/HeapReachingDefs.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/slicer/PDG.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/slicer/SDGSupergraph.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/summaries/BypassSyntheticClass.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ssa/SSANewInstruction.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/types/FieldReference.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/types/Selector.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/types/TypeName.java
  com.ibm.wala.core/src/testFixtures/java/com/ibm/wala/core/tests/ir/AnnotationTest.java
  com.ibm.wala.core/src/testSubjects/java/dynamicCG/MainClass.java
  com.ibm.wala.core/src/testSubjects/java/reflection/Reflect3.java
  com.ibm.wala.core/src/testSubjects/java/reflection/Reflect4.java
  com.ibm.wala.core/src/testSubjects/java/reflection/Reflect5.java
  com.ibm.wala.core/src/testSubjects/java/reflection/Reflect6.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/AndroidModel.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/FlatInstantiator.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/Instantiator.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/LoadedInstantiationBehavior.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/structure/AbstractAndroidModel.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/stubs/ExternalModel.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/propagation/cfa/Intent.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/propagation/cfa/IntentMap.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/util/AndroidManifestXMLReader.java
  com.ibm.wala.ide/src/main/java/com/ibm/wala/ide/util/HeadlessUtil.java
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/MonitorUtil.java
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/intset/SemiSparseMutableIntSet.java
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/processes/Launcher.java
Labels: cleanup

#986 Conform to Java package naming conventions
  com.ibm.wala.core.java11/src/test/java/com/ibm/wala/core/tests/jdk11/privateInterfaceMethods/PrivateInterfaceMethodsTest.java
  com.ibm.wala.core.java11/src/testSubjects/java/privateInterfaceMethods/testArrayReturn/ReturnArray.java
  com.ibm.wala.core.java11/src/testSubjects/java/privateInterfaceMethods/testArrayReturn/TestArrayReturn.java
Labels: cleanup

#990 Remove hundreds of redundant `final` qualifiers
  com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ir/translator/AstTranslator.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/ref/CacheReference.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/strings/Atom.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/types/FieldReference.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/types/MethodReference.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/types/TypeName.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/types/TypeReference.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeCT/SourcePositionTableReader.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/CRTData.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/CRTFlags.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/CRTable.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/MethodPositions.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/sourcepos/Position.java
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/intset/OffsetBitVector.java
Labels: cleanup

#991 `protected` members of `final` classes may as well be `private`
  com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java
  com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/FlowGraph.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/cfg/ShrikeCFG.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/classLoader/ShrikeClass.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/types/TypeReference.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/classLoader/DexCFG.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/util/AndroidEntryPointLocator.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ArrayLengthInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ArrayLoadInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ArrayStoreInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/BinaryOpInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/CheckCastInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ComparisonInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ConditionalBranchInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ConstantInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ConversionInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/DupInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/GotoInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/InstanceofInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/LoadInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/MonitorInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/NewInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/PopInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ReturnInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ShiftInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/StoreInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/SwapInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/SwitchInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/ThrowInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/UnaryOpInstruction.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeCT/SourcePositionTableReader.java
Labels: cleanup

#992 Exclude `other.xml` from Git
  .idea/.gitignore
Labels: cleanup, ide

#993 Double-quote a variable expansion
  run-time-trials
Labels: cleanup

#988 Use higher-level assertion methods where applicable
  com.ibm.wala.cast.java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java
  com.ibm.wala.cast.js/src/testFixtures/java/com/ibm/wala/cast/js/test/TestPointerAnalyses.java
  com.ibm.wala.core/src/testFixtures/java/com/ibm/wala/core/tests/ir/AnnotationTest.java
Labels: cleanup

#997 Use higher-level assertion methods where applicable
  com.ibm.wala.cast.js.nodejs/src/test/java/com/ibm/wala/cast/js/nodejs/test/NodejsRequireJsonTest.java
  com.ibm.wala.cast.js.nodejs/src/test/java/com/ibm/wala/cast/js/nodejs/test/NodejsRequireTargetSelectorResolveTest.java
  com.ibm.wala.cast.js/src/test/java/com/ibm/wala/cast/js/test/TestWebUtil.java
  com.ibm.wala.cast/src/test/java/com/ibm/wala/cast/test/TestCAstPattern.java
  com.ibm.wala.cast/src/test/java/com/ibm/wala/cast/test/TestCAstTranslator.java
  com.ibm.wala.core.java11/src/test/java/com/ibm/wala/core/tests/jdk11/nestmates/NestmatesTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/basic/FloydWarshallTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/basic/PrimitivesTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/basic/WelshPowellTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/AcyclicCallGraphTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/CallGraphTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/ClassConstantTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/ReflectionTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/SyntheticTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/cfg/exc/intra/NullPointerExceptionIntraTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/cha/InterfaceTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/cha/SourceMapTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/ir/CFGTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/ir/CornerCasesTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/ir/DeterministicIRTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/ir/LocalNamesTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/ir/MultiNewArrayTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/ptrs/ObjectSensitiveTest.java
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/typeInference/TypeInferenceTest.java
  com.ibm.wala.ide.jdt.test/src/test/java/com/ibm/wala/cast/java/test/JDTJavaTest.java
Labels: cleanup

#998 Make `private` fields `final` where possible
  com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java
  com.ibm.wala.core.java11/src/testSubjects/java/nestmates/Outer.java
Labels: cleanup

#1002 Remove redundant `unmodifiableCollection` wrapper
  com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/ssa/Util.java
Labels: cleanup

#999 Avoid `int` shifts that implicitly cast to `long`
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/shrikeCT/tools/AddSerialVersion.java
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/math/Logs.java
Labels: cleanup

#1003 Remove gratuitous `new File` creations
  com.ibm.wala.dalvik/src/test/java/com/ibm/wala/dalvik/test/cha/MultiDexScopeTest.java
Labels: cleanup

#1007 Remove a gratuitous unary negation
  com.ibm.wala.cast.java.test.data/src/test/java/StaticInitializers.java
  com.ibm.wala.cast.java.test.data/src/test/java/foo/bar/hello/world/InnerClasses.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/analysis/arraybounds/ArrayBoundsGraph.java
Labels: cleanup

#1008 Specialize String emptiness checks
  com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/JSMethodInstructionVisitor.java
  com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/ipa/summaries/JavaScriptConstructorFunctions.java
Labels: cleanup

#1009 Optimize iterations over Maps' keys and values
  com.ibm.wala.cast.js.rhino/src/test/java/com/ibm/wala/cast/js/test/TestCallGraph2JSON.java
Labels: cleanup

#1010 Use a bulk Map operation instead of explicit iteration
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/collections/BimodalMap.java
Labels: cleanup

#1017 Use official Gradle GitHub actions
  .github/workflows/continuous-integration.yml
  xvfb-gradle.sh
Labels: gradle
