Repository wala/WALA, pull requests merged in 2022-12, with the labels that each got.

#1169 Access a static method via its declaring class
  com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/ReflectionTest.java
Labels: cleanup

#1170 Revamp classpath search to use normalized paths
  com.ibm.wala.core/src/testFixtures/java/com/ibm/wala/core/tests/util/WalaTestCase.java
Labels: windows

#1177 Simplify assertions
  com.ibm.wala.ide.jsdt.tests/src/test/java/com/ibm/wala/ide/jsdt/tests/AbstractJSProjectScopeTest.java
Labels: cleanup

#1180 Don't use Javadoc comments mid-method.
  com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/WorklistBasedOptimisticCallgraphBuilder.java
Labels: cleanup

#1176 Avoid resource leaks when walking the file system
  com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/util/FieldBasedCGUtil.java
  com.ibm.wala.core.java11/src/main/java/com/ibm/wala/core/java11/JrtModule.java
Labels: cleanup

#1179 Don't use bare URLs in Javadoc comments
  com.ibm.wala.cast.js.nodejs/src/main/java/com/ibm/wala/cast/js/nodejs/NodejsRequireTargetSelector.java
  com.ibm.wala.cast.js.nodejs/src/main/java/com/ibm/wala/cast/js/nodejs/NodejsRequiredCoreModule.java
  com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ir/ssa/analysis/LiveAnalysis.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/cha/ClassHierarchyFactory.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/summaries/LambdaMethodTargetSelector.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ssa/IR.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/util/androidEntryPoints/ApplicationEP.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/util/androidEntryPoints/FragmentEP.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/shrikeCT/tools/AddSerialVersion.java
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/PlatformUtil.java
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/io/FileUtil.java
Labels: cleanup

#1178 Remove redundant array length checks
  com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/ir/translator/AstTranslator.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/cfg/ShrikeCFG.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/SSAPropagationCallGraphBuilder.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/classLoader/DexCFG.java
  com.ibm.wala.scandroid/src/main/java/org/scandroid/flow/InflowAnalysis.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/Util.java
Labels: cleanup

#1181 Replace null checks with equivalent method calls
  com.ibm.wala.cast.js.rhino/src/main/java/com/ibm/wala/cast/js/translator/RhinoToAstTranslator.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/analysis/exceptionanalysis/ExceptionAnalysis.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/ssa/ParameterAccessor.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/demandpa/util/SimpleMemoryAccessMap.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ipa/callgraph/androidModel/parameters/LoadedInstantiationBehavior.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/util/AndroidEntryPointLocator.java
  com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/util/AndroidEntryPointManager.java
Labels: cleanup

#1182 Use String.repeat() where applicable
  com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/html/DefaultSourceExtractor.java
  com.ibm.wala.cast.js/src/testFixtures/java/com/ibm/wala/cast/js/test/CAstDumper.java
  com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/strings/StringStuff.java
  com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrike/shrikeBT/shrikeCT/tools/ClassPrinter.java
  com.ibm.wala.util/src/main/java/com/ibm/wala/util/tables/Table.java
Labels: cleanup

#1185 Enlarge Gradle daemon's metaspace size limit
  gradle.properties
Labels: gradle

#1186 Set $JAVA_HOME for Android SDK installer
  com.ibm.wala.dalvik/build.gradle.kts
Labels: gradle

#1190 Gather dependency versions in a version catalog
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/kotlin/com/ibm/wala/gradle/JavaCompileUsingEcj.kt
  buildSrc/src/main/kotlin/com/ibm/wala/gradle/NullAway.gradle.kts
  buildSrc/src/main/kotlin/com/ibm/wala/gradle/java.gradle.kts
  com.ibm.wala.cast.java.ecj/build.gradle.kts
  com.ibm.wala.cast.java/build.gradle.kts
  com.ibm.wala.cast.js.html.nu_validator/build.gradle.kts
  com.ibm.wala.cast.js.nodejs/build.gradle.kts
  com.ibm.wala.cast.js.rhino/build.gradle.kts
  com.ibm.wala.cast.js/build.gradle.kts
  com.ibm.wala.cast/build.gradle.kts
  com.ibm.wala.core.java11/build.gradle.kts
  com.ibm.wala.core/build.gradle.kts
  com.ibm.wala.dalvik/build.gradle.kts
  com.ibm.wala.ide.jdt.test/build.gradle.kts
  com.ibm.wala.ide.jdt/build.gradle.kts
  com.ibm.wala.ide.jsdt.tests/build.gradle.kts
  com.ibm.wala.ide.jsdt/build.gradle.kts
  com.ibm.wala.ide.tests/build.gradle.kts
  com.ibm.wala.ide/build.gradle.kts
  com.ibm.wala.scandroid/build.gradle.kts
  com.ibm.wala.util/build.gradle.kts
  gradle/libs.versions.toml
Labels: gradle, cleanup

#1193 Use Eclipse 4.21.0 on all platforms
  build.gradle.kts
  gradle/libs.versions.toml
Labels: gradle

#1192 Update to Error Prone 2.17.0
  gradle/libs.versions.toml
Labels: dependencies

#1194 Remove an unnecessary dependency
  com.ibm.wala.core/build.gradle.kts
Labels: gradle, cleanup
